#!/bin/bash
#记录一些变量和函数
. /home/wk/auto/function/environment


elements=(Mg Al Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Ba Ce Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi)


#运行的日志文件
results="results"
errors="errors"
logs="logs"


result(){
    if [ $1 -eq 0 ]; then
        echo "Successfully run $2" >>"$WORK_DIR/results"
    else
        echo "Failed run $2"    >>"$WORK_DIR/results"
    fi
}

logging(){

    if [[ $1 -eq 0 ]];then
        printf '*%.0s' {1..100} >>"$WORK_DIR/logs"
        echo >>"$WORK_DIR/logs" 
        date >>"$WORK_DIR/logs"
        printf '*%.0s' {1..100} >> "$WORK_DIR/errors"
        echo >>"$WORK_DIR/errors" 
        date >>"$WORK_DIR/errors"
        printf '*%.0s' {1..100} >> "$WORK_DIR/results"
        echo >>"$WORK_DIR/results" 
        date >>"$WORK_DIR/results"

    elif [[ $1 -eq 1 ]];then
        printf '=%.0s' {1..50} >> "$WORK_DIR/logs"
        echo >>"$WORK_DIR/logs" 
        date >>"$WORK_DIR/logs"
        echo "bash:  $2" >>"$WORK_DIR/logs"

        printf '=%.0s' {1..50} >> "$WORK_DIR/errors"
        echo >>"$WORK_DIR/errors" 
        date >>"$WORK_DIR/errors"
        echo "bash:  $2" >>"$WORK_DIR/errors"

        printf '=%.0s' {1..50} >> "$WORK_DIR/results"
        echo >>"$WORK_DIR/results" 
        date >>"$WORK_DIR/results"
        echo "bash:  $2" >>"$WORK_DIR/results"
    fi

}

