#!/bin/bash
#若有check-res输出文件，则根据文件内容进行数据提取。否则提取全部数据
source environment
source setting

# default
ROOT_DIR=$(pwd)
command="0"
#不接受外来参数改变
check_file="$WORK_DIR/datas"

# logging
logging 1 "bader-data"

# input
while [[ $# -gt 1 ]]; do
    case "$1" in
        -dir|-D|-d) ROOT_DIR=$2
            echo "ROOT_DIR: $ROOT_DIR" >> "$WORK_DIR/logs"
            shift 2 ;;
        -command|-c|-C) command=$2
            echo "command: $command" >> "$WORK_DIR/logs"
            shift 2 ;;
        --) shift
            break ;;
        *) echo "$1 is not an option" ;;
    esac
done

# main
case "$command" in
    0)
        find "$ROOT_DIR" -type d | while read TARGET_DIR; do
            if [ -z "$(find "$TARGET_DIR" -mindepth 1 -type d)" ]; then
                if [ -f "$TARGET_DIR/AECCAR0" ] && [ -f "$TARGET_DIR/AECCAR2" ]; then
                    cd "$TARGET_DIR"
                    chgsum.pl AECCAR0 AECCAR2 
                    bader CHGCAR -ref CHGCAR_sum
                else
                    echo "$TARGET_DIR no AECCAR"
                fi
            fi
        done
        ;;
    1)
        :
        ;;
    help)
        echo 'this is help'
        ;;
    *)
        echo "$command is not an option"
        ;;
esac

# result
result $? "bader-data"