#!/bin/bash
source /home/wk/auto/function/environment
source /home/wk/auto/function/setting

#default
ROOT_DIR=$(pwd)
file="CHG"
command="0"

#logging
logging 1 "del"

#input
while [[ $# -gt 1 ]] ;do 
    case "$1" in 
        -dir|-D|-d) ROOT_DIR=$2 
            echo "ROOT_DIR: $ROOT_DIR" >> "$WORK_DIR/logs"
            shift 2 ;; 
        -file|-F|-f) file=$2
            echo "file: $file" >> "$WORK_DIR/logs"
            shift 2 ;;    
        --) shift 
            break;; 
        *) echo "$1 is not an option" ;; 
    esac 
   
done

#main
case "$command" in
    0)find "$ROOT_DIR" -type d | while read TARGET_DIR
        do
            if [ -z "$(find "$TARGET_DIR" -mindepth 1 -type d)" ]; then
                rm  "$TARGET_DIR/$file" 2>> $WORK_DIR/errors 1>> $WORK_DIR/logs
            fi
        done ;;
    1)
        :
        ;;
    help)
        echo 'this is help'
        ;;
    *) echo "$command is not an option" ;; 
esac

#result
result $? "del"