#!/bin/bash
#检查计算结果是否正确 ,对正确的结果给出文件夹列表，对错误的结果给出错误信息

source environment
source setting

#default
ROOT_DIR=$(pwd)
file="print_out"
command="0"
match=""

#logging
logging 1 "check-res"

#input
while [[ $# -gt 1 ]] ;do 
    case "$1" in 
        -dir|-D|-d) ROOT_DIR=$2 
            echo "ROOT_DIR: $ROOT_DIR" >> "$WORK_DIR/logs"
            shift 2 ;; 
        -file|-F|-f) file=$2
            echo "file: $file" >> "$WORK_DIR/logs"
            shift 2 ;;   
        -command|-c|-C) command=$2
            echo "command: $command" >> "$WORK_DIR/logs"
            shift 2 ;; 
        -match|-M|-m) match=$2
            echo "match: $match" >> "$WORK_DIR/logs"
            shift 2 ;;
        --) shift 
            break;; 
        *) echo "$1 is not an option" ;; 
    esac    
done

#main
case "$command" in
    0)find "$ROOT_DIR" -type d | while read TARGET_DIR
        do
            if [ -z "$(find "$TARGET_DIR" -mindepth 1 -type d)" ]; then
                if [[ "$TARGET_DIR" == *"$match"* ]];then
                    if [ ! -f "$TARGET_DIR/OUTCAR" ] || ! grep -q "reached" "$TARGET_DIR/OUTCAR" ; then
                        echo " -1 $TARGET_DIR" >>"$WORK_DIR/datas"
                        echo "unexpected end of calculation || $TARGET_DIR" >> "$WORK_DIR/bad_datas"
                    else
                        echo " 1 $TARGET_DIR" >>"$WORK_DIR/datas"
                        echo "$TARGET_DIR" >>"$WORK_DIR/good_datas"
                        grep "E0" "$TARGET_DIR/print_out" | tail -n 1 >>"$WORK_DIR/good_datas"
                        grep -q "reached" "$TARGET_DIR/print_out" >>"$WORK_DIR/good_datas"
                    fi
                fi
            fi
        done ;;
    1)
        :
        ;;
    help)
        echo 'this is help'
        ;;
    *) echo "$command is not an option" ;; 
esac

#result
result $? "check-res"
