#!/bin/bash
#make INCAR POTCAR from POSCAR，copy KPOINTS and vasp.sbatch
#usage: ./xsd-to-input.sh <xsd> <input>
source /home/wk/auto/function/environment
source /home/wk/auto/function/setting

#default
command="0"
TO_DIR=$(pwd)
match=""

#logging
logging 1 "pot-to-all"

#input
while [[ $# -gt 1 ]] ;do 
    case "$1" in  
        -to) TO_DIR=$2
            echo "TO_DIR: $TO_DIR"  >> "$WORK_DIR/logs"
            shift 2 ;;
        -match|-M|-m) match=$2
            echo "match: $match" >> "$WORK_DIR/logs"
            shift 2 ;;
        -command|-c|-C) command=$2
            echo "command: $command" >> "$WORK_DIR/logs"
            shift 2 ;;  
        --) shift 
            break;; 
        *) echo "$1 is not an option" ;; 
    esac 
   
done

#main
case "$command" in
    0)find "$TO_DIR" -type d | while read TARGET_DIR
        do
            if [ -z "$(find "$TARGET_DIR" -mindepth 1 -type d)" ]; then
                if [[ "$TARGET_DIR" == *"$match"* ]];then
                    if [ -f "$TARGET_DIR"/POSCAR ];then
                        IFS=' ' read -r -a eles < <(sed -n '6p' "$TARGET_DIR"/POSCAR | sed 's/\r//g') 2>> $WORK_DIR/errors 1>> $WORK_DIR/logs
                        rm "$TARGET_DIR"/POTCAR 2>> $WORK_DIR/errors 1>> $WORK_DIR/logs
                        for i in "${eles[@]}"    
                            do 
                                if [ -d $pot_dir/"$i" ];then
                                    cat $pot_dir/"$i"/POTCAR >> "$TARGET_DIR"/POTCAR 2>> $WORK_DIR/errors 
                                else
                                    cat $pot_dir/"$i"_sv/POTCAR >> "$TARGET_DIR"/POTCAR 2>> $WORK_DIR/errors 
                                fi
                        done 
                    else
                        echo  " NO POSCAR in $TARGET_DIR" 
                    fi 
                else
                    :
                fi
            fi
        done ;;
    help)
        echo 'this is help'
        ;;
    *) echo "$command is not an option" ;; 
esac

#result
result $? "pot-to-all"

