#!/bin/bash
#the main script(给出一个xsd结构，生成多种元素的vasp输入文件，并运行vasp)
#useage: 
source environment
source setting

#default
command="0"
ROOT_DIR=$(pwd)
match=""
file="POSCAR"
TO_DIR=$(pwd)
screen="OUTCAR"
job_ID_1=0
job_ID_2=1

#logging
logging 0 

#input
while [[ $# -gt 1 ]] ;do 
    case "$1" in 
        -command|-c|-C) command=$2
            echo "command: $command" >> "$WORK_DIR/logs"
            shift 2 ;;
        -dir|-D|-d) ROOT_DIR=$2 
            echo "ROOT_DIR: $ROOT_DIR" >> "$WORK_DIR/logs"
            shift 2 ;;
        -match|-m|-M) match=$2
            echo "match: $match" >> "$WORK_DIR/logs"
            shift 2 ;;
        -file|-F|-f) file=$2
            echo "file: $file" >> "$WORK_DIR/logs"
            shift 2 ;;
        -to) TO_DIR=$2
            echo "TO_DIR: $TO_DIR" >> "$WORK_DIR/logs"
            shift 2 ;;
        -screen) screen=$2
            echo "screen: $screen" >> "$WORK_DIR/logs"
            shift 2 ;;
        -job) job_ID_1=$2 job_ID_2=$3
            echo "job_ID_1: $job_ID_1" >> "$WORK_DIR/logs"
            echo "job_ID_2: $job_ID_2" >> "$WORK_DIR/logs"
            shift 3 ;;
        --) shift 
            break;; 
        *) echo "$1 is not an option " ;; 
    esac 
done

#main
main(){
    case "$command" in 
        #执行批量vasp的流程 -file <POSCAR> -to <DIR> -match <str>
        0)  echo "command: 执行批量vasp的流程" >> "$WORK_DIR/logs"
            echo "pos-to-all" 
            wk-pos-to-all -f ${file} -to ${TO_DIR} -match ${match}
            echo "pot-to-all"
            wk-pot-to-all -to ${TO_DIR} -match ${match}
            echo "mkf-in-loop"
            for i in KPOINTS vasp.sbatch
              do
                wk-mkf-in-loop -f doc/$i -c 0  -to ${TO_DIR} -match ${match}
              done
            ;;
        #执行批量vaspM-2H to 2H的流程
        1)  echo "command: 执行批量vaspM-2H to 2H的流程" >> "$WORK_DIR/logs" 
            wk-pos-to-all -f ${file} -to ${TO_DIR} -match ${match} -command 2
            wk-pot-to-all -to ${TO_DIR} -match ${match} -command 1
            for i in KPOINTS vasp.sbatch
              do
                wk-mkf-in-loop -f doc/$i -c 0  -to ${TO_DIR} -match ${match}
              done
            ;;
            
        *) echo "command: $command is not defined" ;;
    esac 
}
main

#result
printf '=%.0s' {1..50} >> "$WORK_DIR/results"
echo >>"$WORK_DIR/results"
result $? "main"


